### ISSUE TITLE
Missing versions

### ISSUE THREAD

**Issue by ghost** [AntonioND/palib-archive#1]
PAlib 0912XX STABLE beta
https://sourceforge.net/projects/palibinstallwiz/files/Files%20that%20the%20installer%20will%20download/PAlib0912XX_Beta.zip/download

PAlib 070118 beta
https://web.archive.org/web/20071117185247/http://www.palib.info/downloads/Beta/PAlib070118.7z

PAlib 060903? beta (installer, same as PAlib 060905?)
http://www.mobyware.org/nintendo-ds-os/palib-get-147530.html

PAlib 061006? beta (installer)
http://www.mobyware.org/palib-get-155239.html
https://www.dcemu.co.uk/vbulletin/threads/38219-PAlib-BETA-Beta-2-small-changes

CC @Leseratte10

**Comment by AntonioND** [comment]
Thanks a lot for this! I'll update the branches later today.

**Comment by AntonioND** [comment]
The branches are now updated, thanks again for the links!
